# Validation Data Summary Stats

Summarizes rates of `True` (or equivalent positive values) across all CSV files in `evals/core_bench/validation/`.

Two file structures are present:
- **Label structure** (`*_multi.csv`, `*_cheating.csv`): columns named `label_*`; `True` = selected, empty = False for that label.
- **Direct target** (`*_t2.csv`): a `target` column with explicit `True`/`False` values.
- **3-point scale** (`*_3pointscale.csv`): a numeric `target` column (0/1/2) and a `predicate` column.

In [12]:
import pandas as pd
from pathlib import Path

data_dir = Path("../eval_grading/swe_bench/validation/")

def pct(n, d):
    return f"{n}/{d} ({100*n/d:.1f}%)" if d else "0/0"

## 3-Point Scale Files

`target` is numeric (0/1/2); `predicate` describes the comparison type. Rates shown for each score value and each predicate group.

In [13]:
scale_files = sorted(data_dir.glob("*.csv"))

for path in scale_files:
    df = pd.read_csv(path)
    n_rows = len(df)
    print(f"\n=== {path.name} ({n_rows} rows) ===")

    # Distribution of target values
    counts = df["target"].value_counts().sort_index()
    dist = pd.DataFrame({
        "count": counts,
        "rate": [pct(c, n_rows) for c in counts],
    })
    dist.index.name = "target_value"
    display(dist)

    # Breakdown by predicate if column exists
    if "predicate" in df.columns:
        print("\nBy predicate:")
        grp = df.groupby("predicate")["target"].value_counts().unstack(fill_value=0)
        display(grp)

=== swe_bench_oh1_JM.csv (100 rows) ===

              count            rate
target_value
0                87  87/100 (87.0%)
1                 9    9/100 (9.0%)
3                 4    4/100 (4.0%)

By predicate:

target      0  1  3
predicate
eq         87  9  4

In [11]:
print(scale_files)

[]